steps:
  - id: Sonar Analysis
    name: 'gcr.io/cloud-builders/mvn'
    entrypoint: bash
    args:
      - '-c'
      - |
        mvn clean verify sonar:sonar \
          -Dmaven.test.skip=false \
          -Dsonar.projectKey=miso-back-service \
          -Dsonar.host.url=http://34.67.142.84:9001 \
          -Dsonar.login=sqp_02981685640fc92cd338688fb13ec0903938b848 \
          -Dsonar.qualitygate.wait=true



  - id: Package Image
    name: maven:3.8.5-openjdk-17
    args: [ 'mvn', 'package','-Dmaven.test.skip=true' ]

  - id: Docker Build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f','src/main/docker/Dockerfile.jvm','-t','gcr.io/$PROJECT_ID/${REPO_NAME}:v.${TAG_NAME}', '.']

  - id: Docker push
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push','gcr.io/$PROJECT_ID/${REPO_NAME}:v.${TAG_NAME}' ]
  - id: Deploy Cloud Run
    name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run','deploy','${_IMAGE_NAME}',
            '--image','gcr.io/$PROJECT_ID/${REPO_NAME}:v.${TAG_NAME}',
            '--allow-unauthenticated',
            '--min-instances=1',
            '--max-instances=2',
            '--region=us-central1',
            '--project=$PROJECT_ID' ]
substitutions:
  _IMAGE_NAME: miso-back-service